FROM ubuntu
RUN apt-get update && apt-get -y upgrade && apt-get -y install curl build-essential python3-dev python3-pip
# buckle up
RUN curl -sSL https://get.docker.com/ | sh

# copy the repo
RUN mkdir -p /root/docker-tcp-switchboard/
ADD . /root/docker-tcp-switchboard/
WORKDIR /root/docker-tcp-switchboard/

# install requirements
RUN pip3 install -r requirements.txt

# run the test
WORKDIR /root/docker-tcp-switchboard/travis-ci-test
CMD ./runtest.sh


